-- Migration: 2026_07_19_162803.sql
-- Generated by @bungres/kit at 2026-07-19T16:28:27.407Z
-- Changes: ALTER TABLE categories DROP COLUMN description, ALTER TABLE products ALTER COLUMN price (ALTER COLUMN "price" DROP NOT NULL), ALTER TABLE users ADD COLUMN bio, ALTER TABLE users ADD COLUMN is_active

-- ==== UP ====
ALTER TABLE "categories" DROP COLUMN IF EXISTS "description";
ALTER TABLE "products" ALTER COLUMN "price" DROP NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN DEFAULT TRUE;

-- ==== DOWN ====
ALTER TABLE "categories" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "products" ALTER COLUMN "price" SET NOT NULL;
ALTER TABLE "users" DROP COLUMN IF EXISTS "bio";
ALTER TABLE "users" DROP COLUMN IF EXISTS "is_active";
