-- Migration: 2026_07_17_130906.sql
-- Generated by @bungres/kit at 2026-07-17T13:09:07.002Z
-- Changes: CREATE TABLE logs, CREATE INDEX idx_categories_name ON categories, CREATE INDEX idx_order_items_order_id ON order_items, CREATE INDEX idx_orders_user_id ON orders, CREATE INDEX idx_orders_status ON orders, CREATE INDEX idx_products_store_id ON products, CREATE INDEX idx_products_name ON products, CREATE INDEX idx_reviews_product_id ON reviews, CREATE INDEX idx_reviews_user_id ON reviews, CREATE INDEX idx_reviews_rating ON reviews, CREATE INDEX idx_stores_owner_id ON stores, CREATE INDEX idx_stores_name ON stores, CREATE INDEX idx_tags_name ON tags, CREATE INDEX idx_users_email ON users, CREATE INDEX idx_users_email ON users, CREATE INDEX idx_users_name ON users

CREATE TABLE IF NOT EXISTS "logs" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "level" VARCHAR(50) NOT NULL,
  "message" TEXT NOT NULL,
  "meta" JSONB,
  "tags" TEXT[],
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_categories_name" ON "categories" ("name");
CREATE INDEX IF NOT EXISTS "idx_order_items_order_id" ON "order_items" ("order_id");
CREATE INDEX IF NOT EXISTS "idx_orders_user_id" ON "orders" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_orders_status" ON "orders" ("status");
CREATE INDEX IF NOT EXISTS "idx_products_store_id" ON "products" ("store_id");
CREATE INDEX IF NOT EXISTS "idx_products_name" ON "products" ("name");
CREATE INDEX IF NOT EXISTS "idx_reviews_product_id" ON "reviews" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_reviews_user_id" ON "reviews" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_reviews_rating" ON "reviews" ("rating");
CREATE INDEX IF NOT EXISTS "idx_stores_owner_id" ON "stores" ("owner_id");
CREATE INDEX IF NOT EXISTS "idx_stores_name" ON "stores" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_tags_name" ON "tags" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "idx_users_name" ON "users" ("name");