-- Migration: 2026_07_21_070032.sql
-- Generated by @bungres/kit at 2026-07-21T07:00:35.353Z
-- Changes: CREATE TYPE audit_log_level, CREATE TYPE order_status, CREATE TYPE product_condition, CREATE TYPE user_role, CREATE TABLE users, CREATE TABLE audit_logs, CREATE TABLE brands, CREATE TABLE categories, CREATE TABLE orders, CREATE TABLE stores, CREATE TABLE products, CREATE TABLE order_lines, CREATE TABLE tags, CREATE TABLE product_tags, CREATE TABLE reviews, CREATE MATERIALIZED VIEW daily_sales_mv, CREATE MATERIALIZED VIEW top_selling_products_mv

-- ==== UP ====
-- auditLogLevelEnum
CREATE TYPE "audit_log_level" AS ENUM ('debug', 'info', 'warn', 'error', 'fatal');

-- orderStatusEnum
CREATE TYPE "order_status" AS ENUM ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded');

-- productConditionEnum
CREATE TYPE "product_condition" AS ENUM ('new', 'used', 'refurbished', 'damaged');

-- userRoleEnum
CREATE TYPE "user_role" AS ENUM ('admin', 'moderator', 'user', 'guest');

-- users
CREATE TABLE IF NOT EXISTS "users" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "role" "user_role" NOT NULL DEFAULT 'user',
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "birth_date" DATE,
  "bio" TEXT,
  "preferences" JSONB,
  "last_login_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "idx_users_role" ON "users" ("role");
CREATE INDEX IF NOT EXISTS "idx_users_is_active" ON "users" ("is_active");

-- auditLogs
CREATE TABLE IF NOT EXISTS "audit_logs" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "level" "audit_log_level" NOT NULL,
  "action" VARCHAR(100) NOT NULL,
  "message" TEXT NOT NULL,
  "user_id" UUID CONSTRAINT "audit_logs_user_id_fkey" REFERENCES "users"("id") ON DELETE SET NULL,
  "target_resource" VARCHAR(100),
  "target_id" UUID,
  "ip_address" VARCHAR(45),
  "user_agent" TEXT,
  "meta" JSONB,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_audit_logs_level" ON "audit_logs" ("level");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_action" ON "audit_logs" ("action");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_user_id" ON "audit_logs" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_target_resource_target_id" ON "audit_logs" ("target_resource", "target_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_created_at" ON "audit_logs" ("created_at");

-- brands
CREATE TABLE IF NOT EXISTS "brands" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(100) NOT NULL,
  "slug" VARCHAR(100) UNIQUE,
  "description" TEXT,
  "logo_url" VARCHAR(255),
  "website_url" VARCHAR(255),
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_brands_name" ON "brands" ("name");
CREATE INDEX IF NOT EXISTS "idx_brands_slug" ON "brands" ("slug");

-- categories
CREATE TABLE IF NOT EXISTS "categories" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "slug" VARCHAR(100) UNIQUE,
  "parent_id" UUID CONSTRAINT "categories_parent_id_fkey" REFERENCES "categories"("id") ON DELETE SET NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "sort_order" INTEGER DEFAULT 0,
  "metadata" JSONB,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_categories_name" ON "categories" ("name");
CREATE INDEX IF NOT EXISTS "idx_categories_slug" ON "categories" ("slug");
CREATE INDEX IF NOT EXISTS "idx_categories_parent_id" ON "categories" ("parent_id");

-- orders
CREATE TABLE IF NOT EXISTS "orders" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_number" SERIAL,
  "customer_id" UUID NOT NULL CONSTRAINT "orders_customer_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE,
  "status" "order_status" NOT NULL DEFAULT 'pending',
  "subtotal" NUMERIC NOT NULL,
  "tax" NUMERIC DEFAULT 0,
  "shipping" NUMERIC DEFAULT 0,
  "discount" NUMERIC DEFAULT 0,
  "total" NUMERIC NOT NULL,
  "currency" VARCHAR(3) DEFAULT 'USD',
  "notes" TEXT,
  "shipping_address" JSONB,
  "billing_address" JSONB,
  "shipped_at" TIMESTAMP WITH TIME ZONE,
  "delivered_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_orders_customer_id" ON "orders" ("customer_id");
CREATE INDEX IF NOT EXISTS "idx_orders_order_number" ON "orders" ("order_number");
CREATE INDEX IF NOT EXISTS "idx_orders_status" ON "orders" ("status");
CREATE INDEX IF NOT EXISTS "idx_orders_created_at" ON "orders" ("created_at");

-- stores
CREATE TABLE IF NOT EXISTS "stores" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "owner_id" UUID NOT NULL CONSTRAINT "stores_owner_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "rating" NUMERIC,
  "location" JSONB,
  "business_hours" JSONB,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_stores_owner_id" ON "stores" ("owner_id");
CREATE INDEX IF NOT EXISTS "idx_stores_is_active" ON "stores" ("is_active");

-- products
CREATE TABLE IF NOT EXISTS "products" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "store_id" UUID NOT NULL CONSTRAINT "products_store_id_fkey" REFERENCES "stores"("id") ON DELETE CASCADE,
  "category_id" UUID NOT NULL CONSTRAINT "products_category_id_fkey" REFERENCES "categories"("id") ON DELETE CASCADE,
  "brand_id" UUID CONSTRAINT "products_brand_id_fkey" REFERENCES "brands"("id") ON DELETE SET NULL,
  "sku" VARCHAR(50) UNIQUE,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "price" NUMERIC NOT NULL,
  "compare_at_price" NUMERIC,
  "cost_price" NUMERIC,
  "condition" "product_condition" DEFAULT 'new',
  "stock" INTEGER NOT NULL DEFAULT 0,
  "low_stock_threshold" INTEGER DEFAULT 10,
  "weight" NUMERIC,
  "dimensions" JSONB,
  "images" TEXT[],
  "tags" TEXT[],
  "attributes" JSONB,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "published_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_products_store_id" ON "products" ("store_id");
CREATE INDEX IF NOT EXISTS "idx_products_category_id" ON "products" ("category_id");
CREATE INDEX IF NOT EXISTS "idx_products_brand_id" ON "products" ("brand_id");
CREATE INDEX IF NOT EXISTS "idx_products_name" ON "products" ("name");
CREATE INDEX IF NOT EXISTS "idx_products_sku" ON "products" ("sku");
CREATE INDEX IF NOT EXISTS "idx_products_price" ON "products" ("price");
CREATE INDEX IF NOT EXISTS "idx_products_is_active" ON "products" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_products_condition" ON "products" ("condition");

-- orderLines
CREATE TABLE IF NOT EXISTS "order_lines" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" UUID NOT NULL CONSTRAINT "order_lines_order_id_fkey" REFERENCES "orders"("id") ON DELETE CASCADE,
  "product_id" UUID NOT NULL CONSTRAINT "order_lines_product_id_fkey" REFERENCES "products"("id") ON DELETE RESTRICT,
  "quantity" INTEGER NOT NULL,
  "unit_price" NUMERIC NOT NULL,
  "total_price" NUMERIC NOT NULL,
  "product_name" VARCHAR(255),
  "product_sku" VARCHAR(50),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_order_lines_order_id" ON "order_lines" ("order_id");
CREATE INDEX IF NOT EXISTS "idx_order_lines_product_id" ON "order_lines" ("product_id");

-- tags
CREATE TABLE IF NOT EXISTS "tags" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(50) NOT NULL UNIQUE,
  "slug" VARCHAR(50) UNIQUE,
  "color" VARCHAR(7),
  "description" TEXT,
  "is_active" BOOLEAN DEFAULT TRUE,
  "usage_count" INTEGER DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_tags_name" ON "tags" ("name");
CREATE INDEX IF NOT EXISTS "idx_tags_slug" ON "tags" ("slug");

-- productTags
CREATE TABLE IF NOT EXISTS "product_tags" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "product_id" UUID NOT NULL CONSTRAINT "product_tags_product_id_fkey" REFERENCES "products"("id") ON DELETE CASCADE,
  "tag_id" UUID NOT NULL CONSTRAINT "product_tags_tag_id_fkey" REFERENCES "tags"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_product_tags_product_id_tag_id" ON "product_tags" ("product_id", "tag_id");

-- reviews
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "product_id" UUID NOT NULL CONSTRAINT "reviews_product_id_fkey" REFERENCES "products"("id") ON DELETE CASCADE,
  "user_id" UUID NOT NULL CONSTRAINT "reviews_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE,
  "rating" INTEGER NOT NULL,
  "title" VARCHAR(255),
  "comment" TEXT,
  "pros" TEXT[],
  "cons" TEXT[],
  "is_verified_purchase" BOOLEAN DEFAULT FALSE,
  "is_recommended" BOOLEAN DEFAULT TRUE,
  "helpful_count" INTEGER DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_reviews_product_id" ON "reviews" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_reviews_user_id" ON "reviews" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_reviews_rating" ON "reviews" ("rating");
CREATE INDEX IF NOT EXISTS "idx_reviews_created_at" ON "reviews" ("created_at");

-- dailySalesView
CREATE MATERIALIZED VIEW "daily_sales_mv" AS 
    SELECT
      DATE_TRUNC('day', created_at) as sale_date,
      COUNT(id) as total_orders,
      SUM(total) as total_revenue,
      SUM(discount) as total_discounts
    FROM orders
    WHERE status != 'cancelled'
    GROUP BY DATE_TRUNC('day', created_at)
  ;

-- topSellingProductsView
CREATE MATERIALIZED VIEW "top_selling_products_mv" AS 
    SELECT
      p.id as product_id,
      p.name as product_name,
      COUNT(ol.id) as times_ordered,
      SUM(ol.quantity) as total_quantity_sold,
      SUM(ol.total_price) as total_revenue
    FROM order_lines ol
    JOIN products p ON ol.product_id = p.id
    JOIN orders o ON ol.order_id = o.id
    WHERE o.status != 'cancelled'
    GROUP BY p.id, p.name
  ;


-- ==== DOWN ====
DROP MATERIALIZED VIEW IF EXISTS "top_selling_products_mv";
DROP MATERIALIZED VIEW IF EXISTS "daily_sales_mv";
DROP TABLE IF EXISTS "reviews";
DROP TABLE IF EXISTS "product_tags";
DROP TABLE IF EXISTS "tags";
DROP TABLE IF EXISTS "order_lines";
DROP TABLE IF EXISTS "products";
DROP TABLE IF EXISTS "stores";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "brands";
DROP TABLE IF EXISTS "audit_logs";
DROP TABLE IF EXISTS "users";
DROP TYPE IF EXISTS "user_role";
DROP TYPE IF EXISTS "product_condition";
DROP TYPE IF EXISTS "order_status";
DROP TYPE IF EXISTS "audit_log_level";
