-- Migration: 2026_07_24_040410.sql
-- Generated by @bungres/kit at 2026-07-24T04:04:13.683Z
-- Changes: DROP VIEW daily_sales_mv (for recreation), DROP VIEW top_selling_products_mv (for recreation), CREATE VIEW daily_sales_mv (recreated), CREATE VIEW top_selling_products_mv (recreated)

-- ==== UP ====
DROP MATERIALIZED VIEW IF EXISTS "daily_sales_mv";
DROP MATERIALIZED VIEW IF EXISTS "top_selling_products_mv";
CREATE MATERIALIZED VIEW "daily_sales_mv" AS 
    SELECT
      DATE_TRUNC('day', created_at) as sale_date,
      COUNT(id) as total_orders,
      SUM(total) as total_revenue,
      SUM(discount) as total_discounts
    FROM orders
    WHERE status != 'cancelled'
    GROUP BY DATE_TRUNC('day', created_at)
  ;
CREATE MATERIALIZED VIEW "top_selling_products_mv" AS 
    SELECT
      p.id as product_id,
      p.name as product_name,
      COUNT(ol.id) as times_ordered,
      SUM(ol.quantity) as total_quantity_sold,
      SUM(ol.total_price) as total_revenue
    FROM order_lines ol
    JOIN products p ON ol.product_id = p.id
    JOIN orders o ON ol.order_id = o.id
    WHERE o.status != 'cancelled'
    GROUP BY p.id, p.name
  ;

-- ==== DOWN ====
DROP MATERIALIZED VIEW IF EXISTS "daily_sales_mv";
DROP MATERIALIZED VIEW IF EXISTS "top_selling_products_mv";
CREATE MATERIALIZED VIEW "daily_sales_mv" AS SELECT * FROM (VALUES ('LEGACY_SNAPSHOT_MISSING_SQL')) AS t(c);
CREATE MATERIALIZED VIEW "top_selling_products_mv" AS SELECT * FROM (VALUES ('LEGACY_SNAPSHOT_MISSING_SQL')) AS t(c);
