-- Migration: 2026_07_17_062014.sql
-- Generated by @bungres/kit at 2026-07-17T06:20:14.166Z
-- Changes: CREATE TABLE categories, CREATE TABLE users, CREATE TABLE orders, CREATE TABLE stores, CREATE TABLE products, CREATE TABLE order_items, CREATE TABLE tags, CREATE TABLE product_tags, CREATE TABLE reviews

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- categories
CREATE TABLE IF NOT EXISTS "categories" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(100) NOT NULL,
  "description" TEXT
);

-- users
CREATE TABLE IF NOT EXISTS "users" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- orders
CREATE TABLE IF NOT EXISTS "orders" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" UUID NOT NULL CONSTRAINT "orders_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE,
  "total" NUMERIC NOT NULL,
  "status" VARCHAR(50) NOT NULL DEFAULT 'pending',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- stores
CREATE TABLE IF NOT EXISTS "stores" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "owner_id" UUID NOT NULL CONSTRAINT "stores_owner_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE,
  "name" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- products
CREATE TABLE IF NOT EXISTS "products" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "store_id" UUID NOT NULL CONSTRAINT "products_store_id_fkey" REFERENCES "stores"("id") ON DELETE CASCADE,
  "category_id" UUID NOT NULL CONSTRAINT "products_category_id_fkey" REFERENCES "categories"("id") ON DELETE CASCADE,
  "name" VARCHAR(255) NOT NULL,
  "price" NUMERIC NOT NULL,
  "stock" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- orderItems
CREATE TABLE IF NOT EXISTS "order_items" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" UUID NOT NULL CONSTRAINT "order_items_order_id_fkey" REFERENCES "orders"("id") ON DELETE CASCADE,
  "product_id" UUID NOT NULL CONSTRAINT "order_items_product_id_fkey" REFERENCES "products"("id") ON DELETE RESTRICT,
  "quantity" INTEGER NOT NULL,
  "price" NUMERIC NOT NULL
);

-- tags
CREATE TABLE IF NOT EXISTS "tags" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" VARCHAR(50) NOT NULL UNIQUE
);

-- productTags
CREATE TABLE IF NOT EXISTS "product_tags" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "product_id" UUID NOT NULL CONSTRAINT "product_tags_product_id_fkey" REFERENCES "products"("id") ON DELETE CASCADE,
  "tag_id" UUID NOT NULL CONSTRAINT "product_tags_tag_id_fkey" REFERENCES "tags"("id") ON DELETE CASCADE
);

-- reviews
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "product_id" UUID NOT NULL CONSTRAINT "reviews_product_id_fkey" REFERENCES "products"("id") ON DELETE CASCADE,
  "user_id" UUID NOT NULL CONSTRAINT "reviews_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE,
  "rating" INTEGER NOT NULL,
  "comment" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
