-- Migration: 2026_07_18_065315.sql
-- Generated by @bungres/kit at 2026-07-18T06:53:15.743Z
-- Changes: ALTER TABLE tags ADD COLUMN created_at

ALTER TABLE "tags" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();