import { join, resolve } from "node:path";
import { generateCreateTable } from "@bungres/orm";
import type { TableConfig } from "@bungres/orm";
import type { ResolvedConfig } from "../config.js";
import { loadSchemas, type SchemaEntry } from "../schema-loader.js";
import { diffSchemas, type SchemaSnapshot } from "../differ.js";
import { colorize } from "../utils/colors.js";

// ---------------------------------------------------------------------------
// generate — diff-based SQL migration generator (drizzle-style numbering)
//
// First run:  full CREATE TABLE for every table  → 0001_init.sql
// Later runs: only the changes (ADD COLUMN, CREATE TABLE, etc.) → 0002_*.sql
//
// Schema state is tracked in <migrationsDir>/.snapshot.json
// ---------------------------------------------------------------------------

const SNAPSHOT_FILE = ".snapshot.json";

export async function runGenerate(
  config: ResolvedConfig,
  name?: string
): Promise<void> {
  console.log("@bungres/kit generate: loading schemas...");

  const schemas = await loadSchemas(config.schema);

  if (schemas.length === 0) {
    console.warn(colorize("No table definitions found. Check your schema glob pattern.", "yellow"));
    return;
  }

  const migrationsDir = resolve(config.out);
  await Bun.$`mkdir -p ${migrationsDir}`.quiet();

  // ── Build current snapshot from loaded schemas ────────────────────────────
  const currentSnapshot: SchemaSnapshot = Object.fromEntries(
    schemas.map((s) => [s.config.name, s.config])
  );

  // ── Load previous snapshot (if any) ──────────────────────────────────────
  const snapshotPath = join(migrationsDir, SNAPSHOT_FILE);
  const snapshotFile = Bun.file(snapshotPath);
  const isFirstMigration = !(await snapshotFile.exists());
  const prevSnapshot: SchemaSnapshot = isFirstMigration
    ? {}
    : (JSON.parse(await snapshotFile.text()) as SchemaSnapshot);

  // ── Determine next sequence number ───────────────────────────────────────
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(now.getUTCDate()).padStart(2, "0");
  const HH = String(now.getUTCHours()).padStart(2, "0");
  const MM = String(now.getUTCMinutes()).padStart(2, "0");
  const SS = String(now.getUTCSeconds()).padStart(2, "0");
  
  const prefix = `${yyyy}_${mm}_${dd}_${HH}${MM}${SS}`;
  const filename = name ? `${prefix}_${name}.sql` : `${prefix}.sql`;
  const outPath = join(migrationsDir, filename);

  // ── Diff ──────────────────────────────────────────────────────────────────
  let statements: string[];
  let summary: string[];
  let warnings: string[] = [];

  if (isFirstMigration) {
    // First migration — full schema sorted by FK dependency order
    const sorted = topoSort(schemas);

    statements = [
      ...sorted.flatMap((entry) => [
        `-- ${entry.exportName}`,
        generateCreateTable(entry.config, true),
        ``,
      ]),
    ];
    summary = sorted.map((s) => `CREATE TABLE ${s.config.name}`);
  } else {
    // Subsequent migrations — diff only
    const diff = diffSchemas(prevSnapshot, currentSnapshot);

    if (diff.statements.length === 0) {
      console.log(colorize("\nNo schema changes detected. Nothing to generate.", "yellow"));
      return;
    }

    statements = diff.statements;
    summary = diff.summary;
    warnings = diff.warnings;
  }

  // ── Write migration file ──────────────────────────────────────────────────
  const lines: string[] = [
    `-- Migration: ${filename}`,
    `-- Generated by @bungres/kit at ${new Date().toISOString()}`,
    `-- Changes: ${summary.join(", ")}`,
    ``,
    ...statements,
  ];

  await Bun.write(outPath, lines.join("\n"));

  // ── Save updated snapshot ─────────────────────────────────────────────────
  await Bun.write(snapshotPath, JSON.stringify(currentSnapshot, null, 2));

  console.log(colorize(`\nGenerated: ${outPath}`, "green"));
  console.log(`  Changes:`);
  for (const s of summary) console.log(colorize(`    + ${s}`, "cyan"));

  if (warnings.length > 0) {
    console.warn(colorize(`\n  ⚠️  WARNING: Data Loss Detected!`, "red"));
    for (const w of warnings) console.warn(colorize(`    ! ${w}`, "red"));
    console.warn(colorize(`  Please review the generated migration carefully before applying it.\n`, "yellow"));
  }

  console.log(colorize(`\nRun \`bungres migrate\` to apply it.`, "cyan"));
}

// ---------------------------------------------------------------------------
// Topological sort — referenced tables come before dependents
// ---------------------------------------------------------------------------

function topoSort(schemas: SchemaEntry[]): SchemaEntry[] {
  const byName = new Map<string, SchemaEntry>(
    schemas.map((s) => [s.config.name, s])
  );

  function deps(config: TableConfig): string[] {
    return Object.values(config.columns)
      .map((col) => col.references?.table)
      .filter((t): t is string => t !== undefined && byName.has(t) && t !== config.name);
  }

  const visited = new Set<string>();
  const result: SchemaEntry[] = [];

  function visit(name: string): void {
    if (visited.has(name)) return;
    visited.add(name);
    const entry = byName.get(name);
    if (!entry) return;
    for (const dep of deps(entry.config)) visit(dep);
    result.push(entry);
  }

  for (const schema of schemas) visit(schema.config.name);

  return result;
}
