ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "website_url" VARCHAR(255);
ALTER TABLE "categories" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
ALTER TABLE "tags" ADD COLUMN IF NOT EXISTS "description" TEXT;
